# Generated by Django 5.0.2 on 2024-02-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
