# Generated by Django 5.0.2 on 2024-02-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_academics'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='student_id',
            field=models.CharField(null=True),
        ),
    ]
