# Generated by Django 5.0.2 on 2024-02-09 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_academics_id_alter_academics_student'),
    ]

  
