# Generated by Django 5.0.2 on 2024-02-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_academics_id_alter_academics_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academics',
            old_name='student',
            new_name='student_id',
        ),
    ]
