# Generated by Django 5.0.2 on 2024-02-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_rename_student_academics_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academics',
            name='english',
        ),
    ]
