# Generated by Django 5.0.2 on 2024-02-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_rename_marks_academics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
